# sharaku-jenkins-ciテストセット
# この .jenkins-ci.yml は動作テスト兼サンプル用です。
config:
  env:
    - env_global_A=0
    - env_global_B=1

# ステージ
stages:
  - stage1
  - stage2
  - stage3

# stage1 -> 環境変数動作確認。
# stage2 -> サブディレクトリ動作確認。
# stage3 -> 並列実行動作確認。
stage:
  stage1:
    node: master
    env:
     - env_global_B="stage1_over_write"
     - env_local_A="C"
     - env_local_B="D"
    script:
     - sh: echo "stage1 env_global_A=${env_global_A} env_global_B=${env_global_B} env_local_A=${env_local_A} env_local_B=${env_local_B}"

  stage2:
    subproject: test

  stage3:
    parallel:
     - stage1
     - stage2
    post:
      always:
       - sh: echo "stage3 post always"
      success:
       - sh: echo "stage3 post success"
      failure:
       - sh: echo "stage3 post failure"
